export const STRING_BAEKMOOK = "백묵"
export const STRING_REGISTER_COMPLETE = "가입이 완료되었습니다!"
export const STRING_UNKNOWN_ERROR = "알 수 없는 오류가 발생했습니다."

export const STRING_ENROLL = "수강신청"
export const STRING_ENROLLED = "수강중"
export const STRING_ENROLL_CONFIRM_DIALOG_TITLE = "정말 수강신청하시겠습니까?"
export const STRING_ENROLL_CONFIRM_DIALOG_SUBTITLE = "한 번 수강신청하면 탈출할 수 없습니다."
export const STRING_LECTURE_ENROLL_COMPLETED = "수강신청이 완료되었습니다!"
export const STRING_NOTICE_EMPTY = "공지사항이 없습니다."
export const STRING_CANCEL = "취소"

export const STRING_LOGIN = "로그인"
export const STRING_LOGOUT = "로그아웃"
export const STRING_LOGIN_PROCESSING = "로그인 중…"
export const STRING_LOGIN_REQUIRED = "로그인이 필요합니다."
export const STRING_LOGIN_TITLE = "백묵 로그인"
export const STRING_EMAIL = "이메일"
export const STRING_PASSWORD = "비밀번호"
export const STRING_WELCOME_MESSAGE = "환영합니다, {0}님!"
export const STRING_GOODBYE_MESSAGE = "다음에 다시 만나요!"

export const STRING_REGISTER = "회원가입"
export const STRING_REGISTER_TITLE = "백묵 회원가입"
export const STRING_EMAIL_REQUIRED = "이메일을 입력해주세요."
export const STRING_NAME = "이름"
export const STRING_NAME_REQUIRED = "이름을 입력해주세요."
export const STRING_PASSWORD_REQUIRED = "비밀번호를 입력해주세요."
export const STRING_PASSWORD_DOES_NOT_MATCH = "비밀번호가 일치하지 않습니다."
export const STRING_PASSWORD_CHECK = "비밀번호 확인"
export const STRING_STUDENT_ID = "학번"
export const STRING_STUDENT_ID_REQUIRED = "학번을 입력해주세요."
export const STRING_JOB = "직업"
export const STRING_JOB_STUDENT = "학생"
export const STRING_JOB_LECTURER = "교수자"

export const STRING_DASHBOARD = "대시보드"
export const STRING_LECTURE = "강의"
export const STRING_MYPAGE = "마이페이지"
export const STRING_MY_LECTURE = "내 강의"

export const STRING_OPEN_LECTURE = "강의 개설"
export const STRING_LECTURE_NAME = "이름"
export const STRING_LECTURE_DESCRIPTON = "소개문구"
export const STRING_OPEN_LECTURE_COMPLETE = "강의 개설이 완료되었습니다!"

export const STRING_NOTICE = "공지사항"
export const STRING_WRITE_POST = "게시글 작성"
export const STRING_TITLE = "제목"
export const STRING_WRITE_CONTENT_PLACEHOLDER = "본문 작성..."
export const STRING_POST_SUBMIT = "작성"

export const STRING_DEFAULT_EMPTY = "표시할 내용이 없습니다."
export const STRING_LECTURE_NON_EXISTENT = "존재하지 않는 강의입니다."
export const STRING_LACK_OF_AUTHORITY = "권한이 없습니다."
export const STRING_GO_BACK = "돌아가기"
